#!/bin/Groovy
pipeline {
    agent any
    stages {
        stage('What is your name') {
           
            steps {
                echo 'My name is Abiodun'
                
            }
        }
        stage('Check date') {
           
            steps {
                sh 'date'
               
            }
        }
        stage('Check calendar') {
           
            steps {
                sh 'cal'
               
            }
        }
         stage('Class') {
           
            steps {
                echo 'i love this class >> niko.txt'
               
            }
        }
         stage('situation') {
           
            steps {
                echo 'nigerian network cut cheche off'
               
            }
        }
         stage('honourable cheche') {
           
            steps {
                sh 'touch alliance.sh'
               
            }
         }
          stage('cheche') {
           
            steps {
                sh 'touch agbaby.sh'
               
            }
         } 
          stage('solution') {
           
            steps {
                echo 'repair the network'
               
            }
        }
    }
}
